### PR TITLE
Move pdfmake from devDependencies to dependencies

### PR DESCRIPTION
**Pull request by tanem**
... since [that appears to be](https://github.com/xErik/pdfmake-browserified/blob/master/src/pdfmake.js#L7) what it is :smiley:

### CODE REVIEW

**Comment by xErik** [comment]
Thanks for your pull request!

`pdfmake` is not required to run the module. It is only needed to build the minified `pdfmake-browserified.min.js` in the `build` directory. Building seems to be a part of development.

But I am not sure if there is an (unofficial) node convention for these kind of things, I am not a node expert :-)

Is this an inconvenience or a blocker for you?
Please let me now, I am willing to change it, if it is an improvement.

**Comment by xErik** [comment]
It is not possible to use `pdfmake-browserified` without building it. The same is true for `pdfmake`.

As used PDF library needs to be processed with `brfs`. Which is only possible during development, not production.

**Comment by tanem** [comment]
Hey @xErik, no prob.

We have an app that's built with webpack, and wanted to try this module out during an investigation into using `pdfmake`. We didn't want to use the prebuilt version during the investigation.

With `pdfmake` being a dev dependency, it doesn't get installed when we install this module into our app, which means we can't build it easily with our webpack setup.

In saying that, I can see the intent of this module, given it's named `-browserified`, and it's `main` points to the built file :smile: So I can understand if you'd rather close this PR.

Incidentally, we have [`pdfmake`](https://github.com/bpampuch/pdfmake) working with our webpack setup. It's not running from the pre-built files, but we're building it via our own webpack setup. It just means we have to tweak our own webpack config to do things similar to `pdfmake`'s [`webpack.config.js`](https://github.com/bpampuch/pdfmake/blob/master/webpack.config.js). I've also created a [fork](https://github.com/tanem/pdfmake/tree/relax-npmignore) which allows us to access the [browser-extensions](https://github.com/tanem/pdfmake/tree/relax-npmignore/src/browser-extensions) used during the build process.

**Comment by xErik** [comment]
Building your own version sounds good, I needed to do the same and created `pdfmake-browserified`. 

It would be more convenient if one simply could use `pdfmake` "out of the box" :-)

**Pull request closed without merging**
