### PR TITLE
Updated pdfMake Libraries and Directory Structure

### PR DESCRIPTION
**Pull request by magbeat**
Hi xErik,

thanks for pdfmake-browserified! We updated the pdfMake libraries and adapted the directory structure to the pdfMake directory structure. Feel free to add comments, make suggestion or merge the pull request.

Thanks again!

Best regards,
Markus

### CODE REVIEW

**Comment by yohanology** [comment]
Hey magbeat! I got this error when trying your commit:

`Uncaught TypeError: Cannot set property 'href' of undefined`

**Comment by xErik** [comment]
Thanks for the pull request, I will test it out tomorrow.

**Comment by yohanology** [comment]
So I removed the window.location.href, and replaced with window.open() to make it work.

**Comment by magbeat** [comment]
@yohanology Thanks for testing the pull request and the feedback! We didn't get the error on our side. This would actually be the original pdfMake source code. Maybe there is an issue with some browsers? Maybe you could report the issue at the pdfMake repository as well?

**Pull request closed without merging**
